// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteUni.Data;

#nullable disable

namespace RestauranteUni.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611005522_MenuAndMenuItemv2")]
    partial class MenuAndMenuItemv2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("RestauranteUni.Domain.Accounts.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("RestauranteUni.Domain.Accounts.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_type");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Professional"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Owner"
                        });
                });

            modelBuilder.Entity("RestauranteUni.Domain.Accounts.Roles.RoleAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<int>("RoleStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_status");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_accounts", (string)null);
                });

            modelBuilder.Entity("RestauranteUni.Domain.Restaurants.Menus.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("restaurant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f58e8cb-2936-4a18-b71f-6d8e0f9e91b0"),
                            Active = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Teste",
                            RestaurantId = new Guid("9a88024d-2618-4e25-87f5-35217f7a7c8a")
                        });
                });

            modelBuilder.Entity("RestauranteUni.Domain.Restaurants.Menus.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("TEXT")
                        .HasColumnName("menu_id");

                    b.Property<int>("PreparationTimeInMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("preparation_time_in_minutes");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("MenuId");

                    b.HasIndex("MenuId", "DisplayOrder");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("RestauranteUni.Domain.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_restaurants_cnpj");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_restaurants_email");

                    b.ToTable("restaurants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a88024d-2618-4e25-87f5-35217f7a7c8a"),
                            Active = true,
                            Cnpj = "12345678000195",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Restaurante principal do campus com refeicoes acessiveis para estudantes.",
                            Email = "ru@restauranteuni.com",
                            Name = "Restaurante Universitario",
                            Phone = "1133334444"
                        },
                        new
                        {
                            Id = new Guid("f02884ad-1725-4fcb-9bb6-cbf0b8f5fef6"),
                            Active = true,
                            Cnpj = "11222333000181",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cantina com lanches, bebidas e opcoes rapidas entre as aulas.",
                            Email = "cantina@restauranteuni.com",
                            Name = "Cantina Central",
                            Phone = "11988887777"
                        },
                        new
                        {
                            Id = new Guid("be0b1f01-0d0f-43e6-9575-b1e117ad62cb"),
                            Active = true,
                            Cnpj = "98765432000198",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Espaco com pratos executivos e opcoes vegetarianas.",
                            Email = "bistro@restauranteuni.com",
                            Name = "Bistro do Campus",
                            Phone = "1130302020"
                        });
                });

            modelBuilder.Entity("RestauranteUni.Domain.Accounts.Roles.RoleAccount", b =>
                {
                    b.HasOne("RestauranteUni.Domain.Accounts.Account", "Account")
                        .WithMany("RoleAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteUni.Domain.Accounts.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RestauranteUni.Domain.Restaurants.Menus.Menu", b =>
                {
                    b.HasOne("RestauranteUni.Domain.Restaurants.Restaurant", "Restaurant")
                        .WithOne("Menu")
                        .HasForeignKey("RestauranteUni.Domain.Restaurants.Menus.Menu", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestauranteUni.Domain.Restaurants.Menus.MenuItem", b =>
                {
                    b.HasOne("RestauranteUni.Domain.Restaurants.Menus.Menu", "Menu")
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RestauranteUni.Domain.Restaurants.Restaurant", b =>
                {
                    b.OwnsOne("RestauranteUni.Domain.ValuesObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_complement");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_district");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");

                            b1.HasData(
                                new
                                {
                                    RestaurantId = new Guid("9a88024d-2618-4e25-87f5-35217f7a7c8a"),
                                    City = "Sao Paulo",
                                    Complement = "Bloco A",
                                    District = "Centro",
                                    Number = "1000",
                                    State = "SP",
                                    Street = "Avenida Universitaria",
                                    ZipCode = "01001000"
                                },
                                new
                                {
                                    RestaurantId = new Guid("f02884ad-1725-4fcb-9bb6-cbf0b8f5fef6"),
                                    City = "Sao Paulo",
                                    Complement = "Praca de alimentacao",
                                    District = "Vila Academica",
                                    Number = "250",
                                    State = "SP",
                                    Street = "Rua dos Estudantes",
                                    ZipCode = "01002000"
                                },
                                new
                                {
                                    RestaurantId = new Guid("be0b1f01-0d0f-43e6-9575-b1e117ad62cb"),
                                    City = "Sao Paulo",
                                    Complement = "Predio 2",
                                    District = "Campus Norte",
                                    Number = "45",
                                    State = "SP",
                                    Street = "Alameda das Ciencias",
                                    ZipCode = "01003000"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteUni.Domain.Accounts.Account", b =>
                {
                    b.Navigation("RoleAccounts");
                });

            modelBuilder.Entity("RestauranteUni.Domain.Restaurants.Menus.Menu", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RestauranteUni.Domain.Restaurants.Restaurant", b =>
                {
                    b.Navigation("Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
