// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaizesDoNordeste.Data;

#nullable disable

namespace RaizesDoNordeste.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614191807_HasDataMenuItemIngredient")]
    partial class HasDataMenuItemIngredient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("RaizesDoNordeste.Domain.Accounts.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Accounts.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_type");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Professional"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Owner"
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Accounts.Roles.RoleAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<int>("RoleStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_status");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_accounts", (string)null);
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Ingredients.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Menus.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("restaurant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Teste",
                            PublicId = new Guid("9a88024d-2618-4e25-87f5-35217f7a7c8b"),
                            RestaurantId = new Guid("9a88024d-2618-4e25-87f5-35217f7a7c8a")
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Menus.MenuItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<long>("MenuId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("menu_id");

                    b.Property<int>("PreparationTimeInMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("preparation_time_in_minutes");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("MenuId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("MenuId", "DisplayOrder");

                    b.ToTable("menu_item", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hambúrguer artesanal com queijo e salada",
                            DisplayOrder = 1,
                            ImageUrl = "/images/xburger.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            MenuId = 1L,
                            PreparationTimeInMinutes = 15,
                            Price = 29.90m,
                            PublicId = new Guid("9a88024d-2618-4e25-87f5-35217f7a7c9b"),
                            Title = "X-Burger"
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pizza tradicional de calabresa",
                            DisplayOrder = 2,
                            ImageUrl = "/images/calabresa.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            MenuId = 1L,
                            PreparationTimeInMinutes = 25,
                            Price = 59.90m,
                            PublicId = new Guid("2a88024d-2618-4e25-87f5-35217f7a7c9b"),
                            Title = "Pizza Calabresa"
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Refrigerante lata",
                            DisplayOrder = 3,
                            ImageUrl = "/images/coca350.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            MenuId = 1L,
                            PreparationTimeInMinutes = 1,
                            Price = 6.50m,
                            PublicId = new Guid("7a88024d-2618-4e25-87f5-35217f7a7c9b"),
                            Title = "Coca-Cola 350ml"
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Menus.MenuItemIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("MenuItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("menu_item_id");

                    b.Property<long?>("MenuItemId1")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<long?>("StockIngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_ingredient_id");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("MenuItemId1");

                    b.HasIndex("StockIngredientId");

                    b.ToTable("menu_item_ingredient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MenuItemId = 1L,
                            Quantity = 0.5m,
                            StockIngredientId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            MenuItemId = 1L,
                            Quantity = 0.2m,
                            StockIngredientId = 2L
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_restaurants_cnpj");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_restaurants_email");

                    b.ToTable("restaurants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a88024d-2618-4e25-87f5-35217f7a7c8a"),
                            Active = true,
                            Cnpj = "12345678000195",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Restaurante principal do campus com refeicoes acessiveis para estudantes.",
                            Email = "ru@RaizesDoNordeste.com",
                            Name = "Restaurante Universitario",
                            Phone = "1133334444"
                        },
                        new
                        {
                            Id = new Guid("f02884ad-1725-4fcb-9bb6-cbf0b8f5fef6"),
                            Active = true,
                            Cnpj = "11222333000181",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cantina com lanches, bebidas e opcoes rapidas entre as aulas.",
                            Email = "cantina@RaizesDoNordeste.com",
                            Name = "Cantina Central",
                            Phone = "11988887777"
                        },
                        new
                        {
                            Id = new Guid("be0b1f01-0d0f-43e6-9575-b1e117ad62cb"),
                            Active = true,
                            Cnpj = "98765432000198",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Espaco com pratos executivos e opcoes vegetarianas.",
                            Email = "bistro@RaizesDoNordeste.com",
                            Name = "Bistro do Campus",
                            Phone = "1130302020"
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Stocks.Stock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("restaurant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("stock", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublicId = new Guid("00000000-0000-0000-0000-000000000001"),
                            RestaurantId = new Guid("9a88024d-2618-4e25-87f5-35217f7a7c8a")
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Stocks.StockIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<long?>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StockId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("StockId");

                    b.HasIndex("StockId1");

                    b.ToTable("stock_ingredient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tomate",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Quantity = 100m,
                            StockId = 1L,
                            Unit = 3
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alface",
                            PublicId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Quantity = 50m,
                            StockId = 1L,
                            Unit = 3
                        });
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Accounts.Roles.RoleAccount", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Accounts.Account", "Account")
                        .WithMany("RoleAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaizesDoNordeste.Domain.Accounts.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Menus.Menu", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Restaurants.Restaurant", "Restaurant")
                        .WithOne("Menu")
                        .HasForeignKey("RaizesDoNordeste.Domain.Menus.Menu", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Menus.MenuItem", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Menus.Menu", "Menu")
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Menus.MenuItemIngredient", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Menus.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId");

                    b.HasOne("RaizesDoNordeste.Domain.Menus.MenuItem", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("MenuItemId1");

                    b.HasOne("RaizesDoNordeste.Domain.Stocks.StockIngredient", "StockIngredient")
                        .WithMany()
                        .HasForeignKey("StockIngredientId");

                    b.Navigation("MenuItem");

                    b.Navigation("StockIngredient");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Restaurants.Restaurant", b =>
                {
                    b.OwnsOne("RaizesDoNordeste.Domain.ValuesObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_complement");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_district");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");

                            b1.HasData(
                                new
                                {
                                    RestaurantId = new Guid("9a88024d-2618-4e25-87f5-35217f7a7c8a"),
                                    City = "Sao Paulo",
                                    Complement = "Bloco A",
                                    District = "Centro",
                                    Number = "1000",
                                    State = "SP",
                                    Street = "Avenida Universitaria",
                                    ZipCode = "01001000"
                                },
                                new
                                {
                                    RestaurantId = new Guid("f02884ad-1725-4fcb-9bb6-cbf0b8f5fef6"),
                                    City = "Sao Paulo",
                                    Complement = "Praca de alimentacao",
                                    District = "Vila Academica",
                                    Number = "250",
                                    State = "SP",
                                    Street = "Rua dos Estudantes",
                                    ZipCode = "01002000"
                                },
                                new
                                {
                                    RestaurantId = new Guid("be0b1f01-0d0f-43e6-9575-b1e117ad62cb"),
                                    City = "Sao Paulo",
                                    Complement = "Predio 2",
                                    District = "Campus Norte",
                                    Number = "45",
                                    State = "SP",
                                    Street = "Alameda das Ciencias",
                                    ZipCode = "01003000"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Stocks.Stock", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Restaurants.Restaurant", "Restaurant")
                        .WithOne("Stock")
                        .HasForeignKey("RaizesDoNordeste.Domain.Stocks.Stock", "RestaurantId");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Stocks.StockIngredient", b =>
                {
                    b.HasOne("RaizesDoNordeste.Domain.Stocks.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId");

                    b.HasOne("RaizesDoNordeste.Domain.Stocks.Stock", null)
                        .WithMany("Items")
                        .HasForeignKey("StockId1");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Accounts.Account", b =>
                {
                    b.Navigation("RoleAccounts");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Menus.Menu", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Menus.MenuItem", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Restaurants.Restaurant", b =>
                {
                    b.Navigation("Menu");

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("RaizesDoNordeste.Domain.Stocks.Stock", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}

